function getColumns(){
		var column_header= [
		                	{"id":"selectVIPBILL","name":"VIP运单",
		                	  	"columns":[
	                			  			 {"field":"billno","title":"运单号","width":"80","sortable":true},
	                			  			 {"field":"ytb","title":"已同步","width":"60","sortable":true},
	                			  			 {"field":"postdate","title":"托运日期","width":"120","sortable":true},
	                			  			 {"field":"ddh","title":"清单号","width":"100","sortable":true},
	                			  			 {"field":"postnet","title":"postnet","width":"150","sortable":true,hidden:true},
	                			  			 {"field":"postzone","title":"postzone","width":"150","sortable":true,hidden:true},
	                			  			 {"field":"postzone_cn","title":"始发地","width":"150","sortable":true},
	                			  			 {"field":"postman","title":"发货人","width":"80","sortable":true},
	                			  			 {"field":"postdw","title":"发货单位","width":"150","sortable":true},
	                			  			 {"field":"posttel","title":"发货人电话","width":"200","sortable":true},
	                			  			 {"field":"postaddr","title":"发货地址","width":"200","sortable":true},
	                			  			 {"field":"acceptnet","title":"acceptnet","width":"150","sortable":true,hidden:true},
	                			  			 {"field":"acceptzone","title":"acceptzone","width":"150","sortable":true,hidden:true},
	                			  			 {"field":"acceptzone_cn","title":"到达地","width":"150","sortable":true},
	                			  			 {"field":"acceptman","title":"收货人","width":"80","sortable":true},
	                			  			 {"field":"acceptdw","title":"收货单位","width":"150","sortable":true},
	                			  			 {"field":"accepttel","title":"收货电话","width":"200","sortable":true},
	                			  			 {"field":"acceptaddr","title":"收货地址","width":"200","sortable":true},
	                			  			 {"field":"boxes","title":"箱数","width":"50","sortable":true,"sum":1},
	                			  			 {"field":"duals","title":"双数","width":"50","sortable":true,"sum":1},
	                			  			 {"field":"volume","title":"体积","width":"50","sortable":true,"sum":1},
	                			  			 {"field":"weight","title":"重量","width":"50","sortable":true,"sum":1},
	                			  			 {"field":"cus_code","title":"客户代码","width":"150","sortable":true},
	                			  			 {"field":"jswd","title":"jswd","width":"150","sortable":true,hidden:true},
	                			  			 {"field":"fkfs","title":"fkfs","width":"150","sortable":true,hidden:true},
	                			  			 {"field":"jjfs","title":"jjfs","width":"150","sortable":true,hidden:true},
	                			  			 {"field":"gg","title":"gg","width":"150","sortable":true,hidden:true},
	                			  			 {"field":"fkfs_cn","title":"付款方式","width":"60","sortable":true},
	                			  			 {"field":"hwlb","title":"hwlb","width":"150","sortable":true,hidden:true},  
	                			  			 {"field":"hwlb_cn","title":"货物类别","width":"60","sortable":true},
	                			  			 {"field":"bjfee","title":"保价费","width":"60","sortable":true},
	                			  			 {"field":"postfee","title":"运费","width":"60","sortable":true},
	                			  			 {"field":"totalprice","title":"费用合计","width":"60","sortable":true},
	                			  			 {"field":"memo","title":"备注","width":"60","sortable":true},  
	                			  			 {"field":"tbbj","title":"tbbj","width":"60","sortable":true,hidden:true},
	                			  			 {"field":"pdbj","title":"tbbj","width":"60","sortable":true,hidden:true},
	                			  	  ]

		                	},
		                	{
		                		"id":"selectLXBILL","name":"拉夏运单",
		                		"columns":[
		                		           {"field":"billno","title":"运单号","width":"100","sortable":true},
		                		           {"field":"acceptzone","title":"到达地","width":"100","sortable":true},
		                		           {"field":"acceptdw","title":"收货单位","width":"300","sortable":true},
		                		           {"field":"acceptaddr","title":"收货地址","width":"300","sortable":true},
		                		           {"field":"acceptman","title":"收货人","width":"80","sortable":true},
		                		           {"field":"accepttel","title":"收货电话","width":"100","sortable":true},
		                		           {"field":"hwlb","title":"货物类别","width":"40","sortable":true},
		                		           {"field":"cusno","title":"客户单号","width":"100","sortable":true},
		                		           {"field":"boxes","title":"箱数","width":"50","sortable":true,"sum":1},
		                		           {"field":"volume","title":"体积","width":"50","sortable":true,"sum":1},
		                		           {"field":"memo","title":"备注","width":"300","sortable":true},
		                		      ]
		                	},
		                	{
		                	"id":"selectLZTH","name":"绫致退货F单导入",
		                		"columns":[
		                		           {"field":"billno","title":"运单号","width":"120","sortable":true},
		                		           {"field":"postdate","title":"托运日期","width":"120","sortable":true},
		                		           {"field":"dpdm","title":"店铺代码","width":"120","sortable":true},
		                		           {"field":"dpmc","title":"店铺名称","width":"200","sortable":true}
		                		      ]
		                	},
		                	{
		                		"id":"selectLZQDHZ","name":"绫致清单汇总",
		                		"columns":[
		                		           {"field":"postdate","title":"托运日期","width":"120","sortable":true},
		                		           {"field":"cfqdh","title":"春风清单号","width":"120","sortable":true},
		                		           {"field":"dpdm","title":"店铺代码","width":"100","sortable":true},
		                		           {"field":"dpmc","title":"店铺名称","width":"300","sortable":true},
		                		           {"field":"ydsl","title":"退单数量","width":"80","sortable":true},
		                		           {"field":"scr","title":"清单生成人","width":"100","sortable":true},
		                		           {"field":"scrq","title":"清单生成日期","width":"140","sortable":true},
		                		      ]
		                	},
		                	{
		                		"id":"selectLZQDMX","name":"绫致清单明细",
		                		"columns":[
		                		           {"field":"billno","title":"退单号","width":"120","sortable":true},
		                		           {"field":"postdate","title":"托运日期","width":"120","sortable":true},
		                		           {"field":"dpdm","title":"店铺代码","width":"100","sortable":true},
		                		           {"field":"dpmc","title":"店铺名称","width":"300","sortable":true},
		                		           {"field":"cfqdh","title":"春风清单号","width":"120","sortable":true},
		                		           {"field":"lrr","title":"导入人","width":"100","sortable":true},
		                		           {"field":"lrrq","title":"导入日期","width":"140","sortable":true},
		                		           {"field":"scr","title":"清单生成人","width":"100","sortable":true},
		                		           {"field":"scrq","title":"清单生成日期","width":"140","sortable":true}
		                		      ]
		                	},
		                ];
		return column_header;
}
