function getColumns(){
	var column_header= [
	                    {"id":"selectPZXX","name":"本网点未配载运单",
	                    	"columns":[ 
	                    	           {"field":"billno","title":"运单号","width":"110","sortable":true,"sortOrder":"asc"},
	                    	           {"field":"postnet","title":"发货网点","width":"70","sortable":true},
	                    	           {"field":"acceptnet","title":"到达网点","width":"70","sortable":true},
	                    	           {"field":"state","title":"运单状态","width":"70","sortable":true},
	                    	           {"field":"POSTDATE","title":"托运日期","width":"120","sortable":true}
	                    	           ]
	                    },	
	                    {"id":"selectPZQD","name":"配载清单(按住Ctrl多选)",
	                    	"columns":[ 
	                    	           {"field":"billno","title":"运单号","width":"130","sortable":true,"sortOrder":"asc","sum":1},
	                    	           {"field":"taskno","title":"派车单号","width":"100","sortable":true},
	                    	           {"field":"cus_name","title":"客户","width":"100","sortable":true},
	                    	           {"field":"postdw","title":"发货单位","width":"100","sortable":true},
	                    	           {"field":"ydsl","title":"录单件数","width":"60","sortable":true,"sum":1},
	                    	           {"field":"items","title":"配载件数","width":"60","sortable":true,"sum":1},
	                    	           {"field":"volume","title":"体积","width":"60","sortable":true,"sum":1},
	                    	           {"field":"pzwd_name","title":"配载到达网点","width":"100","sortable":true},
	                    	           {"field":"postnet_name","title":"运单发货网点","width":"100","sortable":true},
	                    	           {"field":"acceptnet_name","title":"运单到达网点","width":"100","sortable":true},
	                    	           {"field":"counts","title":"干线配载次数","width":"100","sortable":true,"hidden":true},
	                    	           {"field":"czwd_name","title":"操作网点","width":"100","sortable":true},
	                    	           {"field":"czr_name","title":"操作人","width":"100","sortable":true},
	                    	           {"field":"czrq","title":"操作日期","width":"100","sortable":true},
	                    	           {"field":"czwd","title":"czwd","width":"70","sortable":true,"hidden":true},
	                    	           {"field":"postnet","title":"postnet","width":"70","sortable":true,"hidden":true},
	                    	           {"field":"acceptnet","title":"acceptnet","width":"70","sortable":true,"hidden":true},
	                    	           {"field":"pzwd","title":"pzwd","width":"70","sortable":true,"hidden":true},
	                    	           {"field":"ypz","title":"ypz","width":"70","sortable":true,"hidden":true},
	                    	           {"field":"maxitems","title":"maxitems","width":"60","sortable":true,"hidden":true}
	                    	]
	                    },	
	                    {"id":"selectPSPZXX","name":"本网点未配载运单",
	                    	"columns":[ 
	                    	           {"field":"billno","title":"运单号","width":"130","sortable":true,"sortOrder":"asc"},
	                    	           {"field":"postnet","title":"发货网点","width":"70","sortable":true},
	                    	           {"field":"acceptnet","sqlfield":"dept_code","title":"到达网点","width":"70","sortable":true},
	                    	           {"field":"state","sqlfield":"dept_code","title":"运单状态","width":"70","sortable":true}
	                    	           ]
	                    },	
	                    {"id":"selectPSPZQD","name":"配载清单(按住Ctrl多选)",
	                    	"columns":[ 
	                    	           {"field":"billno","title":"运单号","width":"130","sortable":true,"sortOrder":"asc"},
	                    	           {"field":"taskno","title":"派车单号","width":"100","sortable":true},
	                    	           {"field":"items","title":"件数","width":"60","sortable":true,"sum":1},
	                    	           {"field":"postnet_name","title":"运单发货网点","width":"100","sortable":true},
	                    	           {"field":"acceptnet_name","title":"运单到达网点","width":"100","sortable":true},
	                    	           {"field":"czwd_name","title":"操作网点","width":"100","sortable":true},
	                    	           {"field":"czr_name","title":"操作人","width":"100","sortable":true},
	                    	           {"field":"czrq","title":"操作日期","width":"100","sortable":true},
	                    	           {"field":"czwd","title":"czwd","width":"70","sortable":true,"hidden":true},
	                    	           {"field":"ypz","title":"ypz","width":"70","sortable":true,"hidden":true},
	                    	           {"field":"maxitems","title":"maxitems","width":"60","sortable":true,"hidden":true}
	                    	           ]
	                    },
	                    {"id":"selectGXPCD","name":"干线派车单查询",
	                    	"columns":[ 
	                    	           {"field":"taskno","title":"派车单号","width":"100","sortable":true,"sortOrder":"asc"},
	                    	           {"field":"state","title":"当前状态","width":"70","sortable":true},
	                    	           {"field":"nownet","title":"当前网点","width":"80","sortable":true},
	                    	           {"field":"car_num","title":"车牌号 ","width":"100","sortable":true},
	                    	           {"field":"lscar_num","title":"临时车牌号 ","width":"100","sortable":true},
	                    	           {"field":"driver","title":"司机 ","width":"70","sortable":true},
	                    	           {"field":"tel","title":"司机电话 ","width":"90","sortable":true},
	                    	           {"field":"shp_name","title":"承运商 ","width":"90","sortable":true},
	                    	           {"field":"line_name","title":"线路 ","width":"130","sortable":true},
	                    	           {"field":"ps","title":"配载票数 ","width":"80","sortable":true,"sum":1},
	                    	           {"field":"items","title":"配载件数 ","width":"80","sortable":true,"sum":1},
	                    	           {"field":"volume","title":"配载体积 ","width":"80","sortable":true,"sum":1},
	                    	           {"field":"weight","title":"配载重量 ","width":"80","sortable":true,"sum":1},
	                    	           {"field":"c_long","title":"车长 ","width":"70","sortable":true},
	                    	           {"field":"c_width","title":"车宽 ","width":"70","sortable":true},
	                    	           {"field":"c_height","title":"车高 ","width":"70","sortable":true},
	                    	           {"field":"c_volume","title":"承载体积 ","width":"80","sortable":true},
	                    	           {"field":"lrr","title":"调度人 ","width":"70","sortable":true},
	                    	           {"field":"lrrq","title":"调度日期 ","width":"120","sortable":true},
	                    	           {"field":"pzrq","title":"最后配载日期 ","width":"120","sortable":true},
	                    	           {"field":"memo","title":"备注 ","width":"200","sortable":true},
	                    	           ]
	                    },	
	                    {"id":"selectGXQDHZ","name":"干线清单汇总查询",
	                    	"columns":[  
	                    	           {"field":"acceptnet_cn","title":"配载到达网点","width":"80","sortable":true,"sortOrder":"asc"},
	                    	           {"field":"acceptnet","title":"acceptnet","width":"60","sortable":true,"hidden":true},
	                    	           {"field":"ps","title":"配载票数 ","width":"60","sortable":true,"sum":1},
	                    	           {"field":"items","title":"配载件数 ","width":"60","sortable":true,"sum":1},
	                    	           {"field":"volume","title":"配载体积 ","width":"60","sortable":true,"sum":1},
	                    	           {"field":"weight","title":"配载重量 ","width":"60","sortable":true,"sum":1},
	                    	           {"field":"czrq","title":"最后配载时间 ","width":"120","sortable":true},
	                    	           {"field":"taskno","title":"taskno","width":"60","sortable":true,"hidden":true},
	                    	          ]
	                    },	
	                    {"id":"selectGXQD","name":"干线清单查询",
	                    	"columns":[ 
	                    	           {"field":"billno","title":"运单号","width":"130","sortable":true,"sortOrder":"asc",
	                    	        	   "formatter": function(value,row,index){
	                    	        	       return '<a href="#" onclick=GXPZCX.getbox("'+row.billno+'","'+row.acceptnet2_code+'","'+row.taskno+'")>'+row.billno+'</a>  '
	                    	        	     } },
	                    	           {"field":"state","title":"当前状态","width":"60","sortable":true},
	                    	           {"field":"acceptnet2","title":"配载到达网点","width":"90","sortable":true},
	                    	           {"field":"postdate","title":"托运日期 ","width":"70","sortable":true},
	                    	           {"field":"postzone","title":"发货地","width":"80","sortable":true},
	                    	           {"field":"postnet","title":"发货网点 ","width":"80","sortable":true},
	                    	           {"field":"postdw","title":"发货单位 ","width":"80","sortable":true},
	                    	           {"field":"acceptzone","title":"到达地 ","width":"80","sortable":true},
	                    	           {"field":"acceptnet","title":"到达网点 ","width":"80","sortable":true},
	                    	           {"field":"ydsl","title":"录单件数","width":"60","sortable":true,"sum":1},
	                    	           {"field":"items","title":"配载件数","width":"60","sortable":true,"sum":1},
	                    	           {"field":"volume","title":"体积","width":"60","sortable":true,"sum":1},
	                    	           {"field":"hwlb","title":"货物类别","width":"70","sortable":true},
	                    	           {"field":"acceptdw","title":"收货单位","width":"150","sortable":true},
	                    	           {"field":"weight","title":"重量","width":"60","sortable":true},
	                    	           {"field":"cus_name","title":"客户","width":"100","sortable":true},
	                    	           {"field":"fkfs","title":"付款方式","width":"60","sortable":true},
	                    	           {"field":"lrr","title":"录单员","width":"60","sortable":true},
	                    	           {"field":"lrrq","title":"录单日期","width":"120","sortable":true},
	                    	           {"field":"czr","title":"配载人","width":"60","sortable":true},
	                    	           {"field":"czrq","title":"配载日期","width":"120","sortable":true},
	                    	           {"field":"acceptnet2_code","title":"acceptnet2_code","width":"60","sortable":true,"hidden":true},
	                    	           {"field":"taskno","title":"派车单号","width":"60","sortable":true},
	                    	           {"field":"memo","title":"备注 ","width":"200","sortable":true},
	                    	          ],
	                    	    
	                    },	
	                    {"id":"selectGXFC","name":"干线发车查询",
	                    	"columns":[ 
	                     	           {"field":"billno","title":"运单号","width":"130","sortable":true,"sortOrder":"asc"},
	                    	           {"field":"taskno","title":"派车单号","width":"100","sortable":true},
	                    	           {"field":"postzone","title":"postzone","width":"100","sortable":true,"hidden":true},
	                    	           {"field":"postzone_name","title":"发货地区","width":"100","sortable":true},
	                    	           {"field":"acceptzone","title":"acceptzone","width":"100","sortable":true,"hidden":true},
	                    	           {"field":"fhwd_name","title":"发货网点","width":"100","sortable":true},
	                    	           {"field":"acceptnet","title":"postnet","width":"100","sortable":true,"hidden":true},
	                    	           {"field":"acceptzone_name","title":"到达地区","width":"100","sortable":true},
	                    	           {"field":"postnet","title":"postnet","width":"100","sortable":true,"hidden":true},
	                    	           {"field":"ddwd_name","title":"到达网点","width":"100","sortable":true},
	                    	           {"field":"state","title":"state","width":"180","sortable":true,"hidden":true},
	                    	           {"field":"bztstate","title":"bztstate","width":"180","sortable":true,"hidden":true},
	                    	           {"field":"taskstate","title":"taskstate","width":"180","sortable":true,"hidden":true},
	                    	           {"field":"acceptnet1","title":"acceptnet1","width":"100","sortable":true,"hidden":true},
	                    	           {"field":"pzddwd_name","title":"配载到达网点","width":"100","sortable":true},
	                    	           {"field":"pzwd_name","title":"配载网点","width":"100","sortable":true},
	                    	           {"field":"czr_name","title":"操作人","width":"100","sortable":true},
	                    	           {"field":"czrq","title":"操作日期","width":"100","sortable":true},
	                    	           {"field":"czwd","title":"czwd","width":"100","sortable":true,"hidden":true},
	                    
	                    	           ]
	                    },
	                    {"id":"selectGXDC","name":"干线到车查询",
	                    	"columns":[ 
	                     	           {"field":"billno","title":"运单号","width":"130","sortable":true,"sortOrder":"asc"},
	                    	           {"field":"taskno","title":"派车单号","width":"100","sortable":true},
	                    	           {"field":"postzone","title":"postzone","width":"100","sortable":true,"hidden":true},
	                    	           {"field":"postzone_name","title":"发货地区","width":"100","sortable":true},
	                    	           {"field":"acceptzone","title":"acceptzone","width":"100","sortable":true,"hidden":true},
	                    	           {"field":"fhwd_name","title":"发货网点","width":"100","sortable":true},
	                    	           {"field":"acceptnet","title":"postnet","width":"100","sortable":true,"hidden":true},
	                    	           {"field":"acceptzone_name","title":"到达地区","width":"100","sortable":true},
	                    	           {"field":"postnet","title":"postnet","width":"100","sortable":true,"hidden":true},
	                    	           {"field":"ddwd_name","title":"到达网点","width":"100","sortable":true},
	                    	           {"field":"state","title":"state","width":"180","sortable":true,"hidden":true},
	                    	           {"field":"bztstate","title":"bztstate","width":"180","sortable":true,"hidden":true},
	                    	           {"field":"taskstate","title":"taskstate","width":"180","sortable":true,"hidden":true},
	                    	           {"field":"acceptnet1","title":"acceptnet1","width":"100","sortable":true,"hidden":true},
	                    	           {"field":"pzddwd_name","title":"配载到达网点","width":"100","sortable":true},
	                    	           {"field":"pzwd_name","title":"配载网点","width":"100","sortable":true},
	                    	           {"field":"czr_name","title":"操作人","width":"100","sortable":true},
	                    	           {"field":"czrq","title":"操作日期","width":"100","sortable":true},
	                    	           {"field":"czwd","title":"czwd","width":"100","sortable":true,"hidden":true},
	                    
	                    	           ]
	                    },
	                    {"id":"selectGXXH","name":"卸货查询",
	                    	"columns":[ 
	                     	           {"field":"billno","title":"运单号","width":"130","sortable":true,"sortOrder":"asc"},
	                    	           {"field":"taskno","title":"派车单号","width":"100","sortable":true},
	                    	           {"field":"postzone","title":"postzone","width":"100","sortable":true,"hidden":true},
	                    	           {"field":"postzone_name","title":"发货地区","width":"100","sortable":true},
	                    	           {"field":"acceptzone","title":"acceptzone","width":"100","sortable":true,"hidden":true},
	                    	           {"field":"fhwd_name","title":"发货网点","width":"100","sortable":true},
	                    	           {"field":"acceptnet","title":"postnet","width":"100","sortable":true,"hidden":true},
	                    	           {"field":"acceptzone_name","title":"到达地区","width":"100","sortable":true},
	                    	           {"field":"postnet","title":"postnet","width":"100","sortable":true,"hidden":true},
	                    	           {"field":"ddwd_name","title":"到达网点","width":"100","sortable":true},
	                    	           {"field":"state","title":"state","width":"180","sortable":true,"hidden":true},
	                    	           {"field":"bztstate","title":"bztstate","width":"180","sortable":true,"hidden":true},
	                    	           {"field":"taskstate","title":"taskstate","width":"180","sortable":true,"hidden":true},
	                    	           {"field":"acceptnet1","title":"acceptnet1","width":"100","sortable":true,"hidden":true},
	                    	           {"field":"pzddwd_name","title":"配载到达网点","width":"100","sortable":true},
	                    	           {"field":"dcwd","title":"到车操作网点","width":"100","sortable":true},
	                    	           {"field":"dcr","title":"到车操作人","width":"100","sortable":true},
	                    	           {"field":"dcrq","title":"到车日期","width":"120","sortable":true},
	                    	           {"field":"xhwd","title":"卸货操作网点","width":"100","sortable":true},
	                    	           {"field":"xhr","title":"卸货操作人","width":"100","sortable":true},
	                    	           {"field":"xhrq","title":"卸货日期","width":"120","sortable":true},
	                    	           {"field":"czwd","title":"czwd","width":"100","sortable":true,"hidden":true},
	                    
	                    	           ]
	                    },
	                    {"id":"selectYXH","name":"卸货查询",
	                    	"columns":[ 
	                     	           {"field":"billno","title":"运单号","width":"130","sortable":true,"sortOrder":"asc"},
	                    	           {"field":"taskno","title":"派车单号","width":"100","sortable":true},
	                    	           {"field":"postzone","title":"postzone","width":"100","sortable":true,"hidden":true},
	                    	           {"field":"postzone_name","title":"发货地区","width":"100","sortable":true},
	                    	           {"field":"acceptzone","title":"acceptzone","width":"100","sortable":true,"hidden":true},
	                    	           {"field":"fhwd_name","title":"发货网点","width":"100","sortable":true},
	                    	           {"field":"acceptnet","title":"postnet","width":"100","sortable":true,"hidden":true},
	                    	           {"field":"acceptzone_name","title":"到达地区","width":"100","sortable":true},
	                    	           {"field":"postnet","title":"postnet","width":"100","sortable":true,"hidden":true},
	                    	           {"field":"ddwd_name","title":"到达网点","width":"100","sortable":true},
	                    	           {"field":"state","title":"state","width":"180","sortable":true,"hidden":true},
	                    	           {"field":"bztstate","title":"bztstate","width":"180","sortable":true,"hidden":true},
	                    	           {"field":"taskstate","title":"taskstate","width":"180","sortable":true,"hidden":true},
	                    	           {"field":"acceptnet1","title":"acceptnet1","width":"100","sortable":true,"hidden":true},
	                    	           {"field":"pzddwd_name","title":"配载到达网点","width":"100","sortable":true},
	                    	           {"field":"czr_name","title":"卸货操作人","width":"100","sortable":true},
	                    	           {"field":"czrq","title":"卸货日期","width":"100","sortable":true},
	                    	           {"field":"czwd","title":"czwd","width":"100","sortable":true,"hidden":true},
	                    	           {"field":"yxh","title":"yxh","width":"100","sortable":true,"hidden":true},
	                    	           ]
	                    },
	                    {"id":"selectPSPCD","name":"派送派车单查询",
	                    	"columns":[ 
	                    	           {"field":"taskno","title":"派车单号","width":"100","sortable":true,"sortOrder":"asc"},
	                    	           {"field":"state","title":"当前状态","width":"70","sortable":true},
	                    	           {"field":"nownet","title":"当前网点","width":"80","sortable":true},
	                    	           {"field":"car_num","title":"车牌号 ","width":"100","sortable":true},
	                    	           {"field":"lscar_num","title":"临时车牌号 ","width":"100","sortable":true},
	                    	           {"field":"driver","title":"司机 ","width":"70","sortable":true},
	                    	           {"field":"tsh_peop","title":"提送货人 ","width":"200","sortable":true},
	                    	           {"field":"tel","title":"司机电话 ","width":"90","sortable":true},
	                    	           {"field":"line_name","title":"线路 ","width":"130","sortable":true},
	                    	           {"field":"thitems","title":"提货件数","width":"80","sortable":true,"sum":1},
	                    	           {"field":"psps","title":"派送票数 ","width":"80","sortable":true,"sum":1},
	                    	           {"field":"items","title":"派送件数 ","width":"80","sortable":true,"sum":1},
	                    	           {"field":"boxes","title":"运单箱数 ","width":"80","sortable":true,"sum":1},
	                    	           {"field":"duals","title":"运单双数 ","width":"80","sortable":true,"sum":1},
	                    	           {"field":"packages","title":"运单包数 ","width":"80","sortable":true,"sum":1},
	                    	           {"field":"volume","title":"配载体积 ","width":"80","sortable":true,"sum":1},
	                    	           {"field":"c_long","title":"车长 ","width":"70","sortable":true},
	                    	           {"field":"c_width","title":"车宽 ","width":"70","sortable":true},
	                    	           {"field":"c_height","title":"车高 ","width":"70","sortable":true},
	                    	           {"field":"c_volume","title":"承载体积 ","width":"80","sortable":true},
	                    	           {"field":"lrr","title":"调度人 ","width":"70","sortable":true},
	                    	           {"field":"lrrq","title":"调度日期 ","width":"120","sortable":true},
	                    	           {"field":"pzrq","title":"派送配载日期 ","width":"120","sortable":true},
	                    	           ]
	                    },
	                    {"id":"selectPSQD","name":"派送清单查询",
	                    	"columns":[ 
	                    	           {"field":"billno","title":"运单号","width":"130","sortable":true,"sortOrder":"asc",
	                    	        	   "formatter": function(value,row,index){
	                    	        	       return '<a href="#" onclick=PSPZCX.getbox("'+row.billno+'","'+row.taskno+'")>'+row.billno+'</a>  '
	                    	        	     },"sum":1},
	                    	           {"field":"state","title":"当前状态","width":"60","sortable":true},
	                    	           {"field":"postdate","title":"托运日期 ","width":"70","sortable":true},
	                    	           {"field":"postzone","title":"发货地","width":"80","sortable":true},
	                    	           {"field":"postnet","title":"发货网点 ","width":"80","sortable":true},
	                    	           {"field":"acceptzone","title":"到达地 ","width":"80","sortable":true},
	                    	           {"field":"acceptnet","title":"到达网点 ","width":"80","sortable":true},
	                    	           {"field":"items","title":"配载件数","width":"60","sortable":true,"sum":1},
	                    	           {"field":"boxes","title":"运单箱数","width":"60","sortable":true,"sum":1},
	                    	           {"field":"duals","title":"运单双数","width":"60","sortable":true,"sum":1},
	                    	           {"field":"packages","title":"运单包数","width":"60","sortable":true,"sum":1},
	                    	           {"field":"volume","title":"配载体积","width":"60","sortable":true,"sum":1},
	                    	           {"field":"postdw","title":"发货单位","width":"150","sortable":true},
	                    	           {"field":"acceptdw","title":"收货单位","width":"70","sortable":true},
	                    	           {"field":"weight","title":"重量","width":"60","sortable":true,"sum":1},
	                    	           {"field":"cus_name","title":"客户","width":"100","sortable":true},
	                    	           {"field":"fkfs","title":"付款方式","width":"60","sortable":true},
	                    	           {"field":"lrr","title":"录单员","width":"60","sortable":true},
	                    	           {"field":"lrrq","title":"录单日期","width":"120","sortable":true},
	                    	           {"field":"czr","title":"配载人","width":"60","sortable":true},
	                    	           {"field":"czrq","title":"配载日期","width":"120","sortable":true},
	                    	           {"field":"taskno","title":"taskno","width":"120","sortable":true,"hidden":true},
	                    	          ],
	                    	    
	                    },	
	                    {"id":"selectTHQD","name":"派送清单查询",
	                    	"columns":[ 
	                    	           {"field":"billno","title":"运单号","width":"130","sortable":true,"sortOrder":"asc"},
	                    	           {"field":"boxno","title":"箱号","width":"150","sortable":true},
	                    	           {"field":"peop_name","title":"提货人 ","width":"80","sortable":true},
	                    	           {"field":"pda_code","title":"PDA编号","width":"80","sortable":true},
	                    	           {"field":"scantime","title":"扫描日期 ","width":"120","sortable":true},
	                    	           {"field":"updatetime","title":"上传日期 ","width":"120","sortable":true},
	                    	           {"field":"acceptzone","title":"到达地 ","width":"150","sortable":true},
	                    	          ],
	                    	    
	                    },
	                    {"id":"selectZYXX","name":"本网点未转运运单",
	                    	"columns":[ 
	                    	           {"field":"billno","title":"运单号","width":"130","sortable":true,"sortOrder":"asc"},
	                    	           {"field":"postnet","title":"发货网点","width":"70","sortable":true},
	                    	           {"field":"acceptnet","title":"到达网点","width":"70","sortable":true},
	                    	           {"field":"acceptzone","title":"到达地","width":"70","sortable":true},
	                    	           {"field":"state","title":"运单状态","width":"70","sortable":true}
	                    	           ]
	                    },
	                    {"id":"selectZYQD","name":"转运清单",
	                    	"columns":[ 
	                    	           {"field":"billno","title":"运单号","width":"130","sortable":true,"sortOrder":"asc"},
	                    	           {"field":"zy_comp","title":"zy_comp","width":"80","sortable":true,"hidden":true},
	                    	           {"field":"zy_comp_cn","title":"转运公司","width":"100","sortable":true},
	                    	           {"field":"zyno","title":"转运单号","width":"80","sortable":true},
	                    	           {"field":"items","title":"件数","width":"60","sortable":true,"sum":1},
	                    	           {"field":"cus_name","title":"客户","width":"180","sortable":true},
	                    	           {"field":"fkfs","title":"付款方式","width":"100","sortable":true},
	                    	           {"field":"lrwd","title":"操作网点","width":"100","sortable":true},
	                    	           {"field":"lrr","title":"操作人","width":"100","sortable":true},
	                    	           {"field":"lrrq","title":"操作日期","width":"100","sortable":true},
	                    	           {"field":"yzy","title":"yzy","width":"70","sortable":true,"hidden":true},
	                    	           ]
	                    },
	                    {"id":"selectMWFC","name":"门卫发车查询",
	                    	"columns":[ 
	                    	           {"field":"taskno","title":"派车单号","width":"100","sortable":true,"sortOrder":"asc"},
	                    	           {"field":"car_num","title":"车牌号 ","width":"100","sortable":true},
	                    	           {"field":"lscar_num","title":"临时车牌号 ","width":"100","sortable":true},
	                    	           {"field":"driver","title":"司机 ","width":"100","sortable":true},
	                    	           {"field":"shp_name","title":"承运商 ","width":"100","sortable":true},
	                    	           {"field":"tel","title":"司机电话 ","width":"100","sortable":true},
	                    	           {"field":"lrr_name","title":"录入人 ","width":"100","sortable":true},
	                    	           {"field":"lrrq","title":"录入日期 ","width":"120","sortable":true},
	                    	           {"field":"lrwd_name","title":"录入网点","width":"100","sortable":true},
	                    	           ]
	                    },
	                    {"id":"selectTEMP","name":"箱号导入",
	                    	"columns":[ 
	                    	           {"field":"billno","title":"运单号","width":"130","sortable":true,"sortOrder":"asc"},
	                    	           {"field":"boxno","title":"箱号","width":"100","sortable":true}
	                    	           ]
	                    },	
	                    {"id":"selectXHCX","name":"箱号导入查询",
	                    	"columns":[ 
	                    	           {"field":"billno","title":"运单号","width":"130","sortable":true,"sortOrder":"asc"},
	                    	           {"field":"boxno","title":"箱号","width":"100","sortable":true},
	                    	           {"field":"vipflag","title":"VIP客户","width":"100","sortable":true}
	                    	           ]
	                    },	
	                    {"id":"selectVIPTEMP","name":"箱号导入",
	                    	"columns":[ 
	                    	           {"field":"billno","title":"运单号","width":"130","sortable":true,"sortOrder":"asc"},
	                    	           {"field":"boxno","title":"箱号","width":"100","sortable":true},
	                    	           {"field":"vipflag","title":"VIP标记","width":"100","sortable":true}
	                    	           ]
	                    },	
	                    {"id":"selectPSHCQD","name":"配载清单(按住Ctrl多选)",
	                    	"columns":[ 
	                    	           {"field":"billno","title":"运单号","width":"130","sortable":true,"sortOrder":"asc"},
	                    	           {"field":"taskno","title":"派车单号","width":"100","sortable":true},
	                    	           {"field":"postnet_name","title":"运单发货网点","width":"100","sortable":true},
	                    	           {"field":"acceptnet_name","title":"运单到达网点","width":"100","sortable":true},
	                    	           {"field":"czwd_name","title":"操作网点","width":"100","sortable":true},
	                    	           {"field":"czr_name","title":"操作人","width":"100","sortable":true},
	                    	           {"field":"czrq","title":"操作日期","width":"100","sortable":true},
	                    	           {"field":"yhc","title":"ypz","width":"70","sortable":true,"hidden":true},
	                    	           {"field":"czwd","title":"czwd","width":"70","sortable":true,"hidden":true}
	                    	           ]
	                    },
	                    {"id":"selectTHRC","name":"提货入仓",
	                    	"columns":[ 
	                    	           {"field":"taskno","title":"派车单号","width":"120","sortable":true,"sortOrder":"asc"},
	                    	           {"field":"billno","title":"运单号","width":"120","sortable":true},
	                    	           {"field":"czr","title":"操作人","width":"120","sortable":true},
	                    	           {"field":"czwd","title":"操作网点","width":"120","sortable":true},
	                    	           {"field":"czrq","title":"操作日期","width":"120","sortable":true},
	                    	           {"field":"ypz","title":"已入站","width":"120","sortable":true,"hidden":true}
	                    	          ]
	                    },
	                    {"id":"selectTHQDCX","name":"提货入仓清单",
	                    	"columns":[ 
	                    	           {"field":"taskno","title":"派车单号","width":"120","sortable":true,"sortOrder":"asc"},
	                    	           {"field":"billno","title":"运单号","width":"120","sortable":true},
	                    	           {"field":"state_cn","title":"已入站","width":"120","sortable":true},
	                    	           {"field":"czr","title":"操作人","width":"120","sortable":true},
	                    	           {"field":"czwd","title":"操作网点","width":"120","sortable":true},
	                    	           {"field":"czrq","title":"操作日期","width":"120","sortable":true}
	                    	          ]
	                    },
	                    {"id":"selectYHQD","name":"本网点可驻场装货运单",
	                    	"columns":[ 
	                    	           {"field":"billno","title":"运单号","width":"130","sortable":true,"sortOrder":"asc"},
	                    	           {"field":"postnet","title":"发货网点编码","width":"70","sortable":true,"hidden":true},
	                    	           {"field":"postnet_name","title":"发货网点","width":"70","sortable":true},
	                    	           {"field":"acceptnet","title":"到达网点编码","width":"70","sortable":true,"hidden":true},
	                    	           {"field":"acceptnet_name","title":"到达网点","width":"70","sortable":true},
	                    	           {"field":"state","sqlfield":"dept_code","title":"运单状态","width":"70","sortable":true}
	                    	           ]
	                    },
	                    {"id":"selectZCZHQD","name":"派车单装货清单",
	                    	"columns":[ 
	                    	           {"field":"lrrq","title":"录入时间","width":"150","sortable":true,"sortOrder":"asc"},
	                    	           {"field":"taskno","title":"派车单号","width":"100","sortable":true,"sortOrder":"asc"},
	                    	           {"field":"state","title":"当前状态","width":"70","sortable":true},
	                    	           {"field":"nownet","title":"当前网点","width":"80","sortable":true},
	                    	           {"field":"car_num","title":"车牌号 ","width":"100","sortable":true},
	                    	           {"field":"lscar_num","title":"临时车牌号 ","width":"100","sortable":true},
	                    	           {"field":"driver","title":"司机 ","width":"70","sortable":true},
	                    	           {"field":"tel","title":"司机电话 ","width":"90","sortable":true},
	                    	           {"field":"shp_name","title":"承运商 ","width":"90","sortable":true},
	                    	           {"field":"line_name","title":"线路 ","width":"130","sortable":true},
	                    	           {"field":"boxes","title":"装货箱数","width":"80","sortable":true,"sum":1},
	                    	           {"field":"zhsl","title":"驻场装货箱数","width":"80","sortable":true,"sum":1},
	                    	           {"field":"sjzhsl","title":"实际装货箱数","width":"80","sortable":true,"sum":1,"styler": function(value,row,index){
	                    						return 'color:red;font-weight:800;';
	                    				}
	                    	           },
	                    	           {"field":"ps","title":"配载票数 ","width":"80","sortable":true,"sum":1},
	                    	           {"field":"items","title":"配载件数 ","width":"80","sortable":true,"sum":1},
	                    	           {"field":"lrr","title":"录入人 ","width":"80","sortable":true}
	                    	           ]
	                    },
	                    {"id":"selectZHYJ","name":"驻场装货",
	                    	"columns":[ 
	                    	           {"field":"taskno","title":"派车单号","width":"70","sortable":true,"sum":1},
	                    	           {"field":"zhsl","title":"装货数量","width":"130","sortable":true,"sortOrder":"asc"},
	                    	           {"field":"sjsl","title":"实际装货数量","width":"130","sortable":true,"sortOrder":"asc","sum":1},
	                    	           {"field":"lrr","title":"录入人编码","width":"130","sortable":true,"sortOrder":"asc","hidden":true},
	                    	           {"field":"lrr_name","title":"录入人","width":"130","sortable":true,"sortOrder":"asc"},
	                    	           {"field":"lrrq","title":"录入日期","width":"130","sortable":true,"sortOrder":"asc"},
	                    	           {"field":"xgr","title":"修改人编码","width":"130","sortable":true,"sortOrder":"asc","hidden":true},
	                    	           {"field":"xgr_name","title":"修改人","width":"130","sortable":true,"sortOrder":"asc"},
	                    	           {"field":"xgrq","title":"修改日期","width":"130","sortable":true,"sortOrder":"asc"},
	                    	           {"field":"shr","title":"审核人编码","width":"130","sortable":true,"sortOrder":"asc","hidden":true},
	                    	           {"field":"shr_name","title":"审核人","width":"130","sortable":true,"sortOrder":"asc"},
	                    	           {"field":"shrq","title":"审核日期","width":"130","sortable":true,"sortOrder":"asc"}
	                    	           ]
	                    },
	                    {"id":"selectZHYJITEM","name":"驻场装货明细",
	                    	"columns":[ 
	                    	           {"field":"taskno","title":"派车单号","width":"70","sortable":true},
	                    	           {"field":"peop_code","title":"装货人编码","width":"130","sortable":true,"sortOrder":"asc","hidden":true},
	                    	           {"field":"peop_name","title":"装货人","width":"130","sortable":true,"sortOrder":"asc"},
	                    	           {"field":"zhsl","title":"装货数量","width":"130","sortable":true,"sortOrder":"asc"}
	                    	           ]
	                    },
	                    {"id":"selectPCDZHSL","name":"派车单装货数量汇总",
	                    	"columns":[ 
	                    	           {"field":"lrrq","title":"录入日期","width":"70","sortable":true,"hidden":true},
	                    	           {"field":"boxes","title":"装货箱数","width":"130","sortable":true,"sortOrder":"asc","sum":1},
	                    	           {"field":"zhsl","title":"实际装货箱数","width":"130","sortable":true,"sortOrder":"asc","sum":1},
	                    	           {"field":"pcdsl","title":"派车单总数","width":"130","sortable":true,"sortOrder":"asc","sum":1}
	                    	           ]
	                    },
	                    {"id":"selectOOXX","name":"OOXX",
	                    	"columns":[ 
	                    	           {"field":"taskno","title":"派车单号","width":"100","sortable":true},
	                    	           {"field":"driver","title":"司机","width":"130","sortable":true,"sortOrder":"asc"},
	                    	           {"field":"car_num","title":"车牌","width":"130","sortable":true},
	                    	           {"field":"sfth","title":"是否提货","width":"130","sortable":true},
	                    	           {"field":"state_cn","title":"是否入站","width":"130","sortable":true},
	                    	           ]
	                    },
	                    ];
	return column_header;
}