function getColumns(){
		var column_header= [
		                	{"id":"selectGCZLITMEGROUPJX","name":"安装情况统计表",
		                		"columns":[
		                		           	{"field":"JLID","title":"序号","width":"100"},
		                		           	{"field":"SPWJ_TM","title":"外机条码","width":"100","hidden":true},
		                		           	{"field":"SPWJ_ID","title":"外机机型编码","width":"100","hidden":true},
		                		        	{"field":"SPWJ_NAME","title":"规格型号","width":"100"},
		                		        	{"field":"SPNJ_TM","title":"内机条码","width":"100","hidden":true},
		                		           	{"field":"SPNJ_ID","title":"内机机型编码","width":"100","hidden":true},
		                		        	{"field":"SPNJ_NAME","title":"内机规格型号","width":"100"},
		                		        	{"field":"NUMBERS","title":"数量","width":"100"}/*,
	                		           		{"field":"spwj_name","title":"外机机型名称","width":"100"},
	                		           		{"field":"spnj_tm","title":"内机条码","width":"100","editor":{
	                		           			"type":"numberbox",
	                		           			"options":{
	                		           				min:0,    
	                		           			    precision:3
	                		           			}
	                		           		}},
	                		           		{"field":"SPNJ_NAME","title":"内机机型编码","width":"100"},
	                		           		{"field":"CUSTOMER_LXR","title":"联系人","width":"100"},
	                		           		{"field":"CUSTOMER_TEL","title":"联系人手机号","width":"100"},
	                		           		{"field":"CUSTOMER_ADDRESS","title":"用户地址","width":"100"}*/
	                		           	]
		                	},
		                	{"id":"selectGCZLITEM","name":"安装情况统计表",
		                		"columns":[
		                		           	{"field":"JLID","title":"序号","width":"100"},
		                		           	{"field":"SPWJ_TM","title":"外机条码","width":"100","hidden":true},
		                		           	{"field":"SPWJ_ID","title":"外机机型编码","width":"100","hidden":true},
		                		        	{"field":"SPWJ_NAME","title":"规格型号","width":"100"},
		                		        	{"field":"SPNJ_TM","title":"内机条码","width":"100","hidden":true},
		                		           	{"field":"SPNJ_ID","title":"内机机型编码","width":"100","hidden":true},
		                		        	{"field":"SPNJ_NAME","title":"内机规格型号","width":"100"},
		                		        	{"field":"NUMBERS","title":"数量","width":"100"}
	                		           	]
		                	},
		                	{"id":"selectGCZLCX","name":"格力空调工程机竣工验收明细表",
		                		"columns":[
		                		        	{"field":"GCZLID","title":"规格型号","width":"100"},
		                		        	{"field":"SPWJ_TM","title":"室 外 机","width":"100"},
	                		           		{"field":"SPWJ_ID","title":"外机机型编码","width":"100"},
	                		           		{"field":"spwj_name","title":"空调安装详细地址","width":"100"},
	                		           		{"field":"spnj_tm","title":"联系人","width":"100"},
	                		           		{"field":"SPNJ_NAME","title":"联系电话","width":"100"}
	                		           	]
		                	},
							{"id":"selectGCZL_sqlserver","name":"工程查询",
		                		"columns":[
		                		        	{"field":"工程编号","title":"工程编号","width":"100"},    
											{"field":"工程名称","title":"工程名称","width":"100"},
											{"field":"网点编号","title":"网点编号","width":"100"},
											{"field":"网点名称","title":"网点名称","width":"100"},
											{"field":"用户姓名","title":"用户姓名","width":"100"},
											{"field":"联系人","title":"联系人","width":"100"},
											{"field":"移动电话","title":"移动电话","width":"100"},
											{"field":"用户地址","title":"用户地址","width":"100"},
											{"field":"邮政编码","title":"邮政编码","width":"100"},
											{"field":"安装日期","title":"安装日期","width":"100"},
											{"field":"区号","title":"区号","width":"100","hidden":true},
											{"field":"电话号码","title":"电话号码","width":"100","hidden":true},
											{"field":"购买日期","title":"购买日期","width":"100"},
											{"field":"销售单位号","title":"销售单位号","width":"100","hidden":true},
											{"field":"商店简称","title":"商店简称","width":"100","hidden":true},
											{"field":"销售类型","title":"销售类型","width":"100","hidden":true},
											{"field":"销售区域代码","title":"销售区域代码","width":"100","hidden":true},
											{"field":"内销售区域代码","title":"内销售区域代码","width":"100","hidden":true},
											{"field":"年份","title":"年份","width":"100","hidden":true}
	                		           	]
		                	},
		                	{"id":"selectGCZLHIT_Page","name":"工程资料查询",
		                		"columns":[
		                					{"field":"cz","title":"操作","width":"180",
		                						"formatter": 
		                							function(value,row,index){
		                						var str ='<a href="#" onclick=GCZLHIT.downFile("'+row.GCZLID+'","'+row.GC_ID+'","格力空调工程机竣工验收明细表（表一）.jasper")>表一</a>';
		                						    str +='&nbsp;&nbsp;&nbsp;&nbsp;<a href="#" onclick=GCZLHIT.downFile("'+row.GCZLID+'","'+row.GC_ID+'","格力空调工程机竣工验收明细表（表二）.jasper")>表二</a>';
		                						    //str +='&nbsp;&nbsp;&nbsp;&nbsp;<a href="#" onclick=GCZLHIT.downFile("'+row.GCZLID+'","合同扫描件")>合同</a>';
		                						    //str +='&nbsp;&nbsp;&nbsp;&nbsp;<a href="#" onclick=GCZLHIT.downFile("'+row.GCZLID+'","发票扫描件")>发票</a>';
		                						    //str +='&nbsp;&nbsp;&nbsp;&nbsp;<a href="#" onclick=GCZLHIT.downFile("'+row.GCZLID+'","工程资料照片")>照片</a>';
		                						    str +='&nbsp;&nbsp;&nbsp;&nbsp;<a href="#" onclick=GCZLHIT.downFile("'+row.GCZLID+'","'+row.GC_ID+'","条码明细表.jasper")>条码</a>';
		                						    str +='&nbsp;&nbsp;&nbsp;&nbsp;<a href="#" onclick=GCZLHIT.downFile("'+row.GCZLID+'","'+row.GC_ID+'","证明.jasper")>证明</a>';
		                						    str +='&nbsp;&nbsp;&nbsp;&nbsp;<a href="#" onclick=GCZLHIT.downFile("'+row.GCZLID+'","'+row.GC_ID+'","清单.jasper")>清单</a>';
		        	  	           				return str;
		            	  	           		}},
		                		        	{"field":"GCZLID","title":"业务编号","width":"100"},
											{"field":"GC_ID","title":"工程编号","width":"100"},
											{"field":"GC_NAME","title":"工程名称","width":"100"},
		                		        	{"field":"GSID","title":"公司代码","width":"100"},
	                		           		{"field":"KHGSID","title":"客户公司代码","width":"100","hidden":true},
	                		           		{"field":"SAVE_DATE","title":"上传日期","width":"100"},
	                		           		{"field":"SAVE_USERID","title":"提交帐号","width":"100"},
	                		           		{"field":"SAVE_USERNAME","title":"提交人","width":"100"},
	                		           		{"field":"STORES_ID","title":"网点编号","width":"100"},
	                		           		{"field":"STORES_NAME","title":"网点名称","width":"100","hidden":true},
	                		           		{"field":"SELLER_ID","title":"销售单位","width":"100","hidden":true},
	                		           		{"field":"SELLER_NAME","title":"销售单位名称","width":"100"},
											{"field":"CUSTOMER_NAME","title":"使用单位/用户姓名","width":"100"},
											{"field":"CUSTOMER_LXR","title":"联系人","width":"100"},
											{"field":"CUSTOMER_TEL","title":"联系人手机号","width":"100"},
											{"field":"CUSTOMER_PHONE_AREACODE","title":"固定电话-区号","width":"100"},
											{"field":"CUSTOMER_PHONE","title":"联系人固定电话","width":"100"},
											{"field":"CUSTOMER_ADDRESS","title":"用户地址","width":"100"},
											{"field":"CUSTOMER_POSTCODE","title":"邮政编码","width":"100"},
											{"field":"BUY_DATE","title":"购买日期","width":"100"},
											{"field":"INSTALL_DATE","title":"安装日期","width":"100"},
											{"field":"SELL_TYPE","title":"销售类型","width":"100"},
											{"field":"SELL_ONE","title":"一级销售区域代码","width":"100"},
											{"field":"SELL_TWO","title":"二级销售区域代码","width":"100"},
											{"field":"YEARS","title":"年份","width":"100"},
											{"field":"BUY_NUMBER","title":"购买总数量","width":"100"},
											{"field":"SDRQ","title":"收单日期","width":"100"},
											{"field":"FENSHU","title":"收单份数","width":"100"},
											{"field":"PROCESS_INSTANCE_ID","title":"流程实例ID","width":"100","hidden":true}
	                		           	]
		                	},
		                	{"id":"selectGCZLBATCHDOWN_Page","name":"工程资料查询",
		                		"columns":[
											{"field":"checkId","title":"复选框","width":"100","checkbox":true},
		                					{"field":"cz","title":"操作","width":"180",
		                						"formatter": 
		                							function(value,row,index){
		                						var str ='<a href="#" onclick=GCZLBATCHDOWN.downFile("'+row.GCZLID+'","'+row.GC_ID+'")>下载附件</a>';
		        	  	           				return str;
		            	  	           		}},
		                		        	{"field":"GCZLID","title":"业务编号","width":"100"},
											{"field":"GC_ID","title":"工程编号","width":"100"},
											{"field":"GC_NAME","title":"工程名称","width":"100"},
		                		        	{"field":"GSID","title":"公司代码","width":"100"},
	                		           		{"field":"KHGSID","title":"客户公司代码","width":"100","hidden":true},
	                		           		{"field":"SAVE_DATE","title":"上传日期","width":"100"},
	                		           		{"field":"SAVE_USERID","title":"提交帐号","width":"100"},
	                		           		{"field":"SAVE_USERNAME","title":"提交人","width":"100"},
	                		           		{"field":"STORES_ID","title":"网点编号","width":"100"},
	                		           		{"field":"STORES_NAME","title":"网点名称","width":"100","hidden":true},
	                		           		{"field":"SELLER_ID","title":"销售单位","width":"100","hidden":true},
	                		           		{"field":"SELLER_NAME","title":"销售单位名称","width":"100"},
											{"field":"CUSTOMER_NAME","title":"使用单位/用户姓名","width":"100"},
											{"field":"CUSTOMER_LXR","title":"联系人","width":"100"},
											{"field":"CUSTOMER_TEL","title":"联系人手机号","width":"100"},
											{"field":"CUSTOMER_PHONE_AREACODE","title":"固定电话-区号","width":"100"},
											{"field":"CUSTOMER_PHONE","title":"联系人固定电话","width":"100"},
											{"field":"CUSTOMER_ADDRESS","title":"用户地址","width":"100"},
											{"field":"CUSTOMER_POSTCODE","title":"邮政编码","width":"100"},
											{"field":"BUY_DATE","title":"购买日期","width":"100"},
											{"field":"INSTALL_DATE","title":"安装日期","width":"100"},
											{"field":"SELL_TYPE","title":"销售类型","width":"100"},
											{"field":"SELL_ONE","title":"一级销售区域代码","width":"100"},
											{"field":"SELL_TWO","title":"二级销售区域代码","width":"100"},
											{"field":"YEARS","title":"年份","width":"100"},
											{"field":"BUY_NUMBER","title":"购买总数量","width":"100"},
											{"field":"PROCESS_INSTANCE_ID","title":"流程实例ID","width":"100","hidden":true}
	                		           	]
		                	},
							{"id":"selectGCZLSDCX_Page","name":"工程收单查询",
		                		"columns":[
		                		        	{"field":"GCZLID","title":"业务编号","width":"100"},
											{"field":"GC_ID","title":"工程编号","width":"100"},
											{"field":"GC_NAME","title":"工程名称","width":"100"},
		                		        	{"field":"GSID","title":"公司代码","width":"100"},
	                		           		{"field":"KHGSID","title":"客户公司代码","width":"100","hidden":true},
	                		           		{"field":"SAVE_DATE","title":"上传日期","width":"100"},
	                		           		{"field":"SAVE_USERID","title":"提交帐号","width":"100"},
	                		           		{"field":"SAVE_USERNAME","title":"提交人","width":"100"},
	                		           		{"field":"STORES_ID","title":"网点编号","width":"100"},
	                		           		{"field":"STORES_NAME","title":"网点名称","width":"100","hidden":true},
	                		           		{"field":"SELLER_ID","title":"销售单位","width":"100","hidden":true},
	                		           		{"field":"SELLER_NAME","title":"销售单位名称","width":"100"},
											{"field":"CUSTOMER_NAME","title":"使用单位/用户姓名","width":"100"},
											{"field":"CUSTOMER_LXR","title":"联系人","width":"100"},
											{"field":"CUSTOMER_TEL","title":"联系人手机号","width":"100"},
											{"field":"CUSTOMER_PHONE_AREACODE","title":"固定电话-区号","width":"100"},
											{"field":"CUSTOMER_PHONE","title":"联系人固定电话","width":"100"},
											{"field":"CUSTOMER_ADDRESS","title":"用户地址","width":"100"},
											{"field":"CUSTOMER_POSTCODE","title":"邮政编码","width":"100"},
											{"field":"BUY_DATE","title":"购买日期","width":"100"},
											{"field":"INSTALL_DATE","title":"安装日期","width":"100"},
											{"field":"SELL_TYPE","title":"销售类型","width":"100"},
											{"field":"SELL_ONE","title":"一级销售区域代码","width":"100"},
											{"field":"SELL_TWO","title":"二级销售区域代码","width":"100"},
											{"field":"YEARS","title":"年份","width":"100"},
											{"field":"BUY_NUMBER","title":"购买总数量","width":"100"},
											{"field":"SDRQ","title":"收单日期","width":"100"},
											{"field":"FENSHU","title":"收单份数","width":"100"},
											{"field":"PROCESS_INSTANCE_ID","title":"流程实例ID","width":"100","hidden":true}
	                		           	]
		                	},
							{"id":"selectKHGSZCINFO_Page","name":"客户公司注册信息查询",
		                		"columns":[
		                		        	{"field":"USERID","title":"登录账号","width":"100"},
											{"field":"USERNAME","title":"所属公司名称","width":"100"},
											{"field":"ROLEID","title":"角色代码","width":"100"},
		                		        	{"field":"ROLENAME","title":"角色名称","width":"100"},
	                		           		{"field":"FLAG","title":"有效","width":"100"},
	                		           		{"field":"LAST_LOGIN_TIME,","title":"最后登录时间","width":"100","hidden":true},
	                		           		{"field":"REGIST_TIME","title":"注册时间","width":"100"},
	                		           		{"field":"SJKHGSID","title":"上级公司代码","width":"100"},
	                		           		{"field":"SJNAME","title":"上级公司","width":"100"},
	                		           		{"field":"GSID","title":"销售公司代码","width":"100"},
	                		           		{"field":"GLNAME","title":"销售公司","width":"100"}
	                		           	]
		                	},
							{"id":"selectGCZLEXECLIMPL_Page","name":"工程资料倒入查询",
		                		"columns":[
											{"field":"ID","title":"序号","width":"100","checkbox":true},
		                		        	{"field":"GCBH","title":"工程编号","width":"100"},    
											{"field":"GC_NAME","title":"工程名称","width":"100"},
											{"field":"STORES_ID","title":"网点编号","width":"100"},
											{"field":"STORES_NAME","title":"网点名称","width":"100"},
											{"field":"CUSTOMER_LXR","title":"联系人","width":"100"},
											{"field":"CUSTOMER_TEL","title":"移动电话","width":"100"},
											{"field":"CUSTOMER_ADDRESS","title":"用户地址","width":"100"},
											{"field":"CUSTOMER_POSTCODE","title":"邮政编码","width":"100"},
											{"field":"INSTALL_DATE","title":"安装日期","width":"100"},
											{"field":"CUSTOMER_PHONE_AREACODE","title":"区号","width":"100","hidden":true},
											{"field":"CUSTOMER_PHONE","title":"电话号码","width":"100","hidden":true},
											{"field":"BUY_DATE","title":"购买日期","width":"100"},
											{"field":"STATE","title":"导入状态","width":"100","formatter": 
		                							function(value,row,index){
		                						var str ='未审核';
												if(value ==1 ){
													str ="已审核";
												}
		        	  	           				return str;
		            	  	           		}},
											{"field":"SELLER_ID","title":"销售单位号","width":"100","hidden":true},
											{"field":"SELLER_NAME","title":"商店简称","width":"100","hidden":true},
											{"field":"SELL_TYPE","title":"销售类型","width":"100","hidden":true},
											{"field":"SELL_ONE","title":"销售区域代码","width":"100","hidden":true},
											{"field":"SELL_TWO","title":"内销售区域代码","width":"100","hidden":true},
		                		           	{"field":"SPWJ_TM","title":"外机条码","width":"100","hidden":true},
		                		           	{"field":"SPWJ_ID","title":"外机机型编码","width":"100","hidden":true},
		                		        	{"field":"SPWJ_NAME","title":"规格型号","width":"100"},
		                		        	{"field":"SPNJ_TM","title":"内机条码","width":"100","hidden":true},
		                		           	{"field":"SPNJ_ID","title":"内机机型编码","width":"100","hidden":true},
		                		        	{"field":"SPNJ_NAME","title":"内机规格型号","width":"100"},
		                		        	{"field":"NUMBERS","title":"数量","width":"100"}
	                		           	]
		                	}
		                ];
		return column_header;
}
